foundation-model-stack/fms-model-optimizer

- fms_mo/modules/linear.py
This PR defines `smoothquant_alpha` as a buffer, so that it gets stored in the model state dictionary and checkpoint. 
This allows to automatically retrieve this value at the time the checkpoint is re-loaded (so that the user does not need to re-define it manually, which is prone to errors) and to use it in the re-computation of the smoothquant_scale that was applied during training.
n/a
small code change
Yes
> Set smoothq_alpha as buffer

- fms_mo/quant/ptq.py
This PR fixes the behavior of `get_act_scales` function, which calculates the activation scales for smoothquant, in the case they have *not* been pre-computed and provided by the user. Before this change, *this function always moved the full model to GPU* (using `model.cuda()`) before computing the activation scales. This is not compatible with operations in CPU-only environments, nor with handling of large models. This PR fixes this issue, by adding an optional `device` argument to the function. If `device` is not passed, computations will not alter the current model device. Otherwise, the selected device will be used (both model and batches will be moved to that device).
n/a
n/a
> Fix device for smoothquant activation scales

- tox.ini
Adding the base Python version means that the `tox` runtime will now use this version instead of the `tox` environment version. It means we can specify the version as is supported by the project.
Closes #23 
Run `tox` from the project root.
> tox: Add base Python version to tox environment

- fms_mo/calib.py
- fms_mo/modules/linear.py
- fms_mo/quant/quantizers.py
Enforcing symmetry of activation clips during calibration, if a symmetric quantizer was chosen. 
Modified observers (`qmodel_calibration` route) and Qdynamic (`qmodel_calibration_new` route).
This PR does not cover all supported symmetric quantizers, only those carrying the `minmax` attribute (for `qmodel_calibration`) or those selected with `qa_mode` ending in `sym` (for `qmodel_calibration_new`).
#22 
n/a
> Fix symmetric behavior (issue #22)

- tutorials/quantization_tutorial.ipynb
in quantization tutorial, `wget` package is not installed by the notebook and therefore errors out when used to get the image from the repository.
```python
import os, wget
IMG_FILE_NAME = 'lion.png'
url = 'https://raw.githubusercontent.com/foundation-model-stack/fms-model-optimizer/main/tutorials/images/' + IMG_FILE_NAME
if not os.path.isfile(IMG_FILE_NAME):
wget.download(url, out=IMG_FILE_NAME)
img = Image.open(IMG_FILE_NAME)
img
```
```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-21-3f698ed880ba> in <cell line: 1>()
----> 1 import os, wget
2 IMG_FILE_NAME = 'lion.png'
3 url = 'https://raw.githubusercontent.com/foundation-model-stack/fms-model-optimizer/main/tut …
```
> fix: Error in quantization notebook tutorial when retrieving image

- pyproject.toml
- tox.ini
Python is a dynamic language and does not use static type checking. It instead prevents typing errors at runtime . It
[mypy](https://github.com/python/mypy) is a standard open source static typing tool for Python which is widely used. This PR adds `mypy` as tox target `mypy`.
Note: The suggestions from `mypy` will be applied to the files in a follow PR and static checking enabled in CI/CD by default.
Partial #33 
Running it: `tox -e mypy`
> Add mypy static checker tool

- fms_mo/utils/calib_data.py
Checks for directory prior to creation. This means if the folder exists, it won't error out and will simply write to the existing folder.
created directory with same name and ran the DQ_SQ script example to verify that it was able to run without error.
- [x ] I have ensured all unit tests pass
> [utils] check if folder exists before attempting to create directory

- .github/workflows/labelpr.yaml
Add workflow to enforce PR category labels as prefixes in the title eg. 'feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert'
> ci: Add workflow for PR labels

- fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
- fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
- fms_mo/aiu_addons/i8i8/i8i8_aiu_op.py
Add support for smoothquant to INT8 AIU addon (adapter, linear module, custom op). Compatible with FMS 0.0.8
> feat: Support for int8 smoothquant

- fms_mo/custom_ext_kernels/triton_kernels.py
- fms_mo/run_quant.py
- fms_mo/training_args.py
1. torch_dtype parsing didn't work with strings
2. minor adjustment on triton code for fp8
previously, `run_quant` with `--torch_dtype float16` will throw an error.
> fix: bug fix and minor changes on triton kernel:

- .gitignore
- .spellcheck-en-custom.txt
- examples/FP8_QUANT/README.md
- fms_mo/dq.py
- fms_mo/modules/linear.py
- fms_mo/quant/ptq.py
- fms_mo/training_args.py
- fms_mo/utils/dq_utils.py
1. config_quant_smooth_lays() always resets qcfg["qskip_lay_name"] and loses user-defined info,
2. act_scales didn't check existing files
3. get_mod_act_scales() and cache_block0() didn't check and cache and use position_embeddings
4. act_scale is usually saved in higher prec but QLinear didn't preserve dtype after scaling
5. try to enable device_map="auto" for easier large model inference
> fix: multiple bug fixes:

- fms_mo/dq.py
- fms_mo/fx/dynamo_utils.py
- fms_mo/training_args.py
When graph breaks happen, last layer cannot be determined accurately in model_analyzer(), i.e. dynamo option. An simpler but limited approach is introduced to address this issue. Currently only enabled for transformers, as 1. transformers often run into graph break, and 2. usually transformers do not have parallel heads at the end.
Issue #71 
If user wants to force last layer to be quantized, it can be done through `qcfg["qspecial_layers"]`, such as `qcfg["qspecial_layers"] = {'lm_head':{'nbits_w':8,'qw_mode':'sawb+','nbits_a':8,'qa_mode':'pact+'}}`
> feat: improve transformers tracing for last layers

- fms_mo/dq.py
- fms_mo/utils/utils.py
in DQ example, when nbits_kvcache=8, context manager will detect incorrect frame, and cause error. The frame we are looking for has `"forward" in cf.f_code.co_name` but in Llama3-8B cases, it will be triggered by "eager_attention_forward", which is one frame earlier than the correct one.
Add one additional check, make sure "self" is in cf.f_locals
run dq example with `nbits_kvcache`=8
> fix: in DQ example, when nbits_kvcache=8, context manager will detect incorrect frame

- fms_mo/modules/linear.py
- fms_mo/run_quant.py
- fms_mo/utils/import_utils.py
- pyproject.toml
- tests/models/conftest.py
- tests/triton_kernels/test_triton_mm.py
`triton` doesn't have a pre-built binary for some systems, like Power or Z. Add a check for imports, and if not available, disable the `triton` option accordingly for a few Linear wrappers.
#75 
test on Power or Z system
> fix: make triton optional for systems without GPUs

- fms_mo/fx/dynamo_utils.py
- fms_mo/fx/utils.py
- pyproject.toml
In PT 2.5.1, default IR from Dynamo is Aten IR instead of FX IR, which technically should still work with our `model_analyzer`, but there was a bug that prevented the correct behavior. Now it's resolved.
if condition was not correctly executed due to a bug.
close #73 
tested dq example with an environment using PT 2.5.1
> fix: a bug that prevented dynamo from working with PT 2.5.1 has been fixed

- README.md
- tox.ini
1. minor bug in `tox.ini` causing Python 3.12 check issue
2. README remove Py3.9 add 3.12
> fix: minor fix from last PR regarding py3.12 upgrades

- fms_mo/custom_ext_kernels/triton_kernels.py
- fms_mo/modules/linear.py
add a flag `truncate_then_accumulate` to allow truncation on partial dot product, i.e. one output from a CUDA instruction, before accumulating into final sum. (Previous behavior is to first accumulate into final sum then truncate.)
> feat: triton matmul kernel adjusted, now is closer to HW behavior

- fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
- fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
1. modified i8i8 add-ons to support Granite architecture in FMS, by registering the adapter steps and adapter for granite. Also unified registration process across models.
2. fixed bug in Linear module string representation printing when bias=False.
> feat: int8 granite addon

- fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
This PR updates the INT8 addon for the AIU to enable running with Tensor Parallel TP > 1.
In particular, it updates the sharding map function `shard_int8_aiu_linear` which defines the sharding configuration (sharding dimension and sharding modality) of each parameter. The configuration is used by FMS functions.
Sharding configuration for a quantized W8A8LinearAIU module:
- weights: always sharded along the appropriate dimension (col/row)
- w_clip_val / w_clip_valn: column-sharded (split on output dim) if per-channel in use, otherwise cloned
- a_clip_val / a_clip_valn (single element tensors): cloned 
- zero_shift: cloned
- smoothquant_scale: row sharded (split on inputs dim) if smoothquant is enabled, otherwise cloned
- qdata: not sharded; this buffer is recreated post-sharding as the …
> feat: INT8 LLM TP>1 enablement

- fms_mo/aiu_addons/gptq/gptq_aiu_op.py
- fms_mo/aiu_addons/i8i8/i8i8_aiu_op.py
- pyproject.toml
This PR updates the syntax of registration of a custom op with pytorch. The purpose of registration is to create a custom operation that can be inserted as custom node in the computational graph without inducing a graph break.
From PyTorch 2.4, new `torch.library` functions have been introduced: 
- `custom_op` replacing `impl`
- `register_fake` replacing `impl_abstract`
They streamline earlier implementations of the custom op registration process. With the new syntax, there is no need for an additional op definition using `torch.library.define`. 
The earlier syntax is deprecated from PyTorch >= 2.6: `impl_abstract` redirects to `register_fake` and throws a warning.
However, the new functions introduce a severe lower bound to `fms-mo`-supported PyTorch versions (>= 2.4), so we may want to …
> feat: Update syntax of custom torch ops

- fms_mo/utils/dq_utils.py
This small PR updates `config_quantize_smooth_layers`, adding support for Granite models with `granite` architecture (i.e., Granite version >= 3.0).
> feat: add granite architecture support for DQ with smoothquant

- fms_mo/utils/qconfig_utils.py
- tests/models/conftest.py
- tests/models/test_model_utils.py
- tests/models/test_qmodelprep.py
- tests/models/test_saveconfig.py
Added the following features to the config save process:
- minimal: Only save non-default valued config entries
- save_list: Save only variables contained in qcfg["save_list"]
- recipe save_list: Same as save_list, but in .json form for long term use
- Added archival timestamp: date and pkg_versions for saved config
Furthermore, this work adds basic testing to ensure the above works.  This testing is in tests/models/test_saveconfig.py, as well as supporting files.
TODO List:
- Audit all current config variables to ensure they are grouped with prefixes if needed
- Fix pylint errors
Addresses #97
Run tests/models/ pytest
- I have added >=1 unit test(s) for every new method I have added.
- I have ensured all unit tests pass
> feat: trimming config save

- fms_mo/prep.py
- fms_mo/quant/ptq.py
- fms_mo/recipes/dq.json
- fms_mo/utils/aiu_utils.py
- fms_mo/utils/dq_utils.py
- fms_mo/utils/qconfig_utils.py
- tests/models/test_saveconfig.py
This PR fixes issues found with the config_save feature added in #103:
- Fixed qconfig_save in qmodel_prep using recipe=qcfg.json instead of fname.  This would cause an error re-running qconfig_save as the JSON was not a list.
- Added 4 tests to ensure the above bug has coverage as well as ensuring JSON save/load is being checked properly.
- Guards the qconfig_save/load from opening non-dictionary/list json files.
- Added smoothq prefix to qcfg variables.
- Added smoothq variables to the default config.
> fix: Config save cleanup

- .spellcheck-en-custom.txt
- examples/AIU_CONVERSION/README.md
- fms_mo/dq.py
- fms_mo/run_quant.py
- fms_mo/training_args.py
- fms_mo/utils/dq_utils.py
- fms_mo/utils/qconfig_utils.py
- tests/test_run_quant.py
Add example of converting and saving the checkpoint of RoBERTa INT8 model after DQ.
In addition, as part of this PR:
- support is added for RoBERTa architecture to run DQ with smoothquant, by initializing `smoothq_scale_layers` and other quantization parameters
- 3 training arguments are added: `save_ckpt`, `save_ckpt_for_aiu`, and `recompute_narrow_weights`
- smoothquant selection is modified from being always enabled in DQ (`qcfg["smoothq"]=True`) to depend on smoothq_alpha selection >= 0, such that passing smoothq_alpha = -1 now disables smoothquant
Closes https://github.com/foundation-model-stack/fms-model-optimizer/issues/116
> feat: Conversion example

- fms_mo/custom_ext_kernels/triton_kernels.py
- fms_mo/custom_ext_kernels/utils.py
- fms_mo/dq.py
- fms_mo/modules/linear.py
- fms_mo/prep.py
- fms_mo/quant/ptq.py
- fms_mo/quant/quantizers.py
- fms_mo/training_args.py
- fms_mo/utils/eval_utils.py
- tests/triton_kernels/test_triton_mm.py
MSB/LSB truncation was not completely enabled in triton kernel previously.
#106 
triton kernel unit test was updated. now MSB truncation case is also included.
> feat: adjust int8 triton to enable msb/lsb truncation

- .gitignore
- fms_mo/quant/quantizers.py
- fms_mo/utils/aiu_utils.py
- fms_mo/utils/qconfig_utils.py
- tests/models/conftest.py
- tests/models/test_model_utils.py
- tests/models/test_mx.py
- tests/models/test_qmodelprep.py
- tests/models/test_save_aiu.py
- tests/models/test_saveconfig.py
- tests/models/test_toymodels.py
Added a new tests/models named test_save_aiu.py.  This includes implementing new "tiny" models for BERT, Llama, and Granite from custom configs that are trimmed down.
Also, several test files have been cleaned up with the new autouse=True fixture for file deletion before a test starts.
Change to tests/models and run `pytest test_save_aiu.py`
> test: Add tests for save_for_aiu functionality w/ tiny models

- examples/GPTQ/README.md
minor typo that messed up the tables, also update lm-eval flag `autogptq=True` to `gptqmodel=True` (both will work, but just to be consistent) 
> fix: Update GPTQ example README.md for typo

- examples/GPTQ/README.md
> docs: Fix README typo

- fms_mo/utils/aiu_utils.py
Small PR to modify the process of checkpoint saving for the AIU (performed by the `save_for_aiu` function), both in the case of per-tensor and per-channel weights.
If SAWB computed clip value is higher than the one from MAX quantizer, then the MAX quantizer clip (an absmax operation) and corresponding integer weights are used.
In the case of per-channel weights, the integer weights are selected on a per-channel basis, effectively merging the SAWB- and MAX-generated integer weights matrices.
Process was tested successfully on relevant INT8 checkpoints.
> feat: add guards to sawb recomputation

- README.md
- fms_mo/custom_ext_kernels/triton_kernels.py
- pyproject.toml
- tests/triton_kernels/test_triton_mm.py
This change moves triton to being an optional package.  An additional guard was added, along with minor changes to the test script.
N/A
Triton tests are now skipped on CI/CD rather than passing via a quick return.
```
tests/triton_kernels/test_triton_mm.py ssssssssssssssssssssssssssssss
```
Locally, on my machine I am getting 9x failures from one of the tests:
```
FAILED tests/triton_kernels/test_triton_mm.py::test_triton_matmul_fp[dtype_to_test4-1024] - AssertionError: assert (tensor(1725.2465, device='cuda:0') / tensor(32604.6211, device='cuda:0')) < 1e-05
```
> build: Move triton to an optional dependency

- README.md
- fms_mo/aiu_addons/gptq/gptq_aiu_adapter.py
- fms_mo/aiu_addons/gptq/gptq_aiu_linear.py
- fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
- fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
- fms_mo/quant/ptq.py
- fms_mo/run_quant.py
- fms_mo/utils/import_utils.py
- pyproject.toml
This PR moves the following dependencies to optional:
- tensorboard, notebook added to `visualize` group
- ninja, evaluate, and huggingface_hub added to `examples` group
- ibm-fms added to `aiu` group
An error check in run_quant.py using huggingface_hub was removed as it wasn't critical.
Additional guards were added to files in aiu_addons to ensure the ibm-fms is installed.
N/A
> build: Make non-essential dependencies optional

- fms_mo/utils/qconfig_utils.py
- tests/models/test_saveconfig.py
This PR fixes a bug for recipes loaded with qconfig_init.  Previous behavior would overwrite any recipe with the qconfig defaults, which is NOT desired.  This now only updates a loaded recipe IF the entry doesn't already exist in the requested qconfig.
Also, a new test was added (`tests/models/test_saveconfig/test_save_init_recipe`) to ensure this behavior is consistent.
Closes #150
Run `pytest tests/models/test_saveconfig.py`
> fix: Saved qconfig recipe being overwritten with defaults

- fms_mo/custom_ext_kernels/utils.py
- fms_mo/modules/linear.py
- fms_mo/utils/custom_gptq_models.py
This change removes the warning for gptqmodel, as well as adds additional safeguards for the optional dependency.
Also, this fixes a minor bug with the available_package check in modules/linear.py, as it was checking for the auto_gptq external kernels instead of gptqmodel's version.
Closes #99
On main:
```shell
python3
>>> import fms_mo
GPTQModel is not properly installed. QLinearExv1WI4AF16 and QLinearExv2WI4AF16 wrappers will not be available.
>>> 
```
This PR:
```shell
python3
>>> import fms_mo
>>> 
```
> fix: Remove gptqmodel Warning on startup

- examples/FP8_QUANT/README.md
- fms_mo/run_quant.py
This PR fixes a warning issued by llmcompressor for a deprecated import.
Closes #145
Run fp8 example.  No deprecated import warning should appear.
> fix: Remove llmcompressor oneshot import deprecation warning

- fms_mo/custom_ext_kernels/triton_kernels.py
- fms_mo/custom_ext_kernels/utils.py
- fms_mo/dq.py
- fms_mo/fx/dynamo_utils.py
- fms_mo/fx/utils.py
- fms_mo/modules/linear.py
- fms_mo/quant/ptq.py
- fms_mo/training_args.py
- fms_mo/utils/dq_utils.py
in addition to INT8 AIU simulation, now FP8 is added to the triton kernel. AIU FP8 is using "DL8" matmul accumulated in "DL16", slightly different from GPU's FP8 e4m3 accum in FP32 (GPU local accumulator only uses ~22bits mantissa).
> feat: AIU sim for FP8 (DL8/DL16) added to triton kernel

- fms_mo/fx/dynamo_utils.py
- fms_mo/quant/ptq.py
`qkvsync` is a function in `model_analyzer` trying to find Linear layers with common input, e.g. Q, K, V, or gate/up (in Llama arch). The results by this searching, a dict like `{"q":"q", "k":"q", "v":"q", ...}`, will be saved in `qcfg["qkvsync_my_1st_siblings"]`. This dict is supposed to contain the **full layer name**, however, when graph breaks happens, `model_analyzer` can only identify partial names instead. Later functions attempt to use `model.get_submodule()` based on this dict will fail.
run dq with bamba (`ibm-ai-platform/Bamba-9B-V2`)
> fix: qkvsync bug fix

- fms_mo/aiu_addons/fp8/fp8_attn.py
- fms_mo/aiu_addons/fp8/fp8_linear.py
- fms_mo/aiu_addons/fp8/fp8_spyre_op.py
- Per-sequence scaling in FP8 attention for both static and continuous batching
- FP8 fixes for the CPU fallback in both eager and torch compile modes
Internal to IBM issue
> feat: Per-sequence scaling in FP8 attention, FP8 fixes

- fms_mo/aiu_addons/fp8/fp8_attn.py
This PR adds an assertion that the FP8 scales have the same batch dimension as the inputs for paged attention. This is important for torch compile to not create extra dynamic dimensions, which is needed for AIU compilation and also accelerates tracing.
Internal AIU issue tracker.
> fix: Mark FP8 scale to have the same batch size as input

- fms_mo/custom_ext_kernels/triton_kernels.py
- fms_mo/run_quant.py
- fms_mo/training_args.py
since ~ a week ago, pylint began to throw a "assignment-from-no-return" warning on `libdevice` functions in triton kernel. disable this false alarm.
> fix: pylint false alarm on libdevice functions

- fms_mo/aiu_addons/fp8/fp8_linear.py
- pyproject.toml
- tox.ini
This PR add version limits for torchao, and fixes compatibility for AIU + the new 0.12 version.
Issue in internal Spyre tracker.
When tracing an FX graph with activations that are dynamically casted to FP8, you should see the following decomposition for the `_quantize_affine_float8` function:
```
_to_copy_8: "f32[1, 128, 4096][524288, 4096, 1]cpu" = torch.ops.aten._to_copy.default(mul_2, dtype = torch.float32)
unsqueeze_3: "f32[1, 128, 1, 1][128, 1, 1, 1]cpu" = torch.ops.aten.unsqueeze.default(_to_copy_7, 3)
expand_1: "f32[1, 128, 1, 4096][128, 1, 1, 0]cpu" = torch.ops.aten.expand.default(unsqueeze_3, [1, 128, 1, 4096]);  unsqueeze_3 = None
clone_1: "f32[1, 128, 1, 4096][524288, 4096, 4096, 1]cpu" = torch.ops.aten.clone.default(expand_1, memory_format = torch.contiguous_format);  expand_1 …
```
> fix: Add version limits for torchao, ensure compat with 0.12 + AIU

- fms_mo/aiu_addons/__init__.py
- fms_mo/aiu_addons/fp8/fp8_attn.py
- pyproject.toml
1. Pin torchao to 0.11 for deliverable
2. Add an error check for torchao being installed when loading fp8 checkpoints
3. Change scaling of Q and K transposed when using fp8 attention.
Internal requests
> feat: FP8 requested changes

- fms_mo/aiu_addons/__init__.py
- fms_mo/aiu_addons/fp8/fp8_linear.py
1. Adds a missing import for FP8 attention (subsumes #175)
2. Fixes the sharding of the weight scales for FP8 TP
This will not work without a PR in FMS (https://github.com/foundation-model-stack/foundation-model-stack/pull/457)
> fix: FP8 TP fixes
